### PR TITLE
Fix compilation and remove build artifacts.

### PR DESCRIPTION
**Pull request by jendrikseipp**
Hi Chris, great job of putting together all these feature extractors! When I tried to build them, I noticed some bitrot. Do you want to incorporate these changes into your repo?

### CODE REVIEW

**Comment by haz** [comment]
Blast from the past :D. For the record, we're hoping to fire this up again and compute everything we can for all the domains in the Planning.Domains API. I have a new 16-machine cluster at my disposal, and computing these features are one of the first things I want to test it out with.

Thanks for the bitfix @jendrikseipp , and let me know if there's anything else that might hold us back, @fawcettc !

**Comment by fawcettc** [comment]
Blast from the past, indeed! Good to hear from you both, and I'm glad that this project is still potentially useful.

These changes all look fine to me, although I'm a bit hesitant to remove the binaries. They may be the only copy of the state used in the paper. Of course, it's also been 5+ years and if I was to do it again I'd just provide a container image for reference purposes. C'est la vie.

@jendrikseipp I assume the inline removals were because clang was complaining about them? I haven't built this project on a recent GCC **or** LLVM version, so I do want to give that a shot before merging this PR.

I'll respond here in a day or two, but I imagine I'll just accept it as-is.

**Comment by jendrikseipp** [comment]
Sounds good! If it helps, I could add a GitHub Action that ensures that everything builds on a recent Ubuntu machine, either in this or a subsequent PR, as you wish.

**Comment by fawcettc** [comment]
Sorry this took forever, I ended up down a bit of a rabbit hole trying to get build the satzilla feature extractor from source. Replacing those binaries is going to be a bit of a problem, as the source for satzilla 2012 hasn't really been maintained. I may have an updated version of this repository in January, though.

In the meantime, I'm accepting this PR. I've verified that this at least allows for a a successful build and feature extraction on Ubuntu 20.04 using the packaged GCC, albeit with some additional dependencies in order to support the SATzilla 32-bit binaries. I'm going to commit a Dockerfile shortly, to demonstrate what is needed.

**Comment by jendrikseipp** [comment]
Thanks!

**Pull request merged**
